### ISSUE TITLE
Leveldb编译出错，fatal error C1075: 与左侧的 大括号“{” 匹配之前遇到文件结束

### ISSUE THREAD

**Issue by malacca** [thinkerou/leveldb_windows#1]
win7 + vs2003 环境生成 leveldb 出错，以下是输出结果，请问是不是还需要配置其他选项，或者安装其他c++库才能编译呢，这个问题应该怎么解决？

> 1>------ 已启动生成:  项目: LevelDB, 配置: Debug Win32 ------
> 1>  testutil.cc
> 1>  testharness.cc
> 1>  status.cc
> 1>  options.cc
> 1>  logging.cc
> 1>  histogram.cc
> 1>  hash.cc
> 1>  filter_policy.cc
> 1>  file_misc.cpp
> 1>e:\leveldb_windows\leveldb\util\file_misc.cpp(51): error C2065: “iDestCount”: 未声明的标识符
> 1>e:\leveldb_windows\leveldb\util\file_misc.cpp(52): error C2065: “iDestCount”: 未声明的标识符
> 1>e:\leveldb_windows\leveldb\util\file_misc.cpp(413): error C2601: “FileMisc::SetFileContent”: 本地函数定义是非法的
> 1>          e:\leveldb_windows\leveldb\util\file_misc.cpp(385):  此行有一个“{”没有匹配项
> 1>e:\leveldb_windows\leveldb\util\file_misc.cpp(424): fatal error C1075: 与左侧的 大括号“{”(位于“e:\leveldb_windows\leveldb\util\file_misc.cpp(385)”)匹配之前遇到文件结束
> 1>  env.cc
> 1>  crc32c.cc
> 1>  comparator.cc
> 1>  coding.cc
> 1>  cache.cc
> 1>  bloom.cc
> 1>  arena.cc
> 1>  two_level_iterator.cc
> 1>  table_builder.cc
> 1>  table.cc
> 1>  merger.cc
> 1>  正在生成代码...
> 1>  正在编译...
> 1>  iterator.cc
> 1>  format.cc
> 1>  filter_block.cc
> 1>  block_builder.cc
> 1>  block.cc
> 1>  port_chromium.cc
> 1>  env_win.cc
> 1>  write_batch.cc
> 1>  version_set.cc
> 1>  version_edit.cc
> 1>  table_cache.cc
> 1>  repair.cc
> 1>  memtable.cc
> 1>  log_writer.cc
> 1>  log_reader.cc
> 1>  leveldb_main.cc
> 1>  filename.cc
> 1>  db_iter.cc
> 1>  db_impl.cc
> 1>  db_bench.cc
> 1>  正在生成代码...
> 1>  正在编译...
> 1>  dbformat.cc
> 1>  c.cc
> 1>  builder.cc
> 1>  正在生成代码...
> ========== 生成:  成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by malacca** [comment]
找到问题所在了

LevelDB/util/file_misc.cpp

第394行的注释引起的问题，真的是心都碎了。

> DWORD dwSize = ::GetFileSize(hFile, NULL);
>         if (dwSize >= 1024 \* 1024 \* 100)
>         {
>                 ::CloseHandle(hFile);
>                 return NULL;    // 如果文件大于100M了，那么就失败吧，一下开那么多内存也不是玩的。
>         }

就是这句中文注释，删了就不报错了，success

**Comment by thinkerou** [comment]
OK, good!
